# Numpy

## What is NumPy?
NumPy stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

## NumPy array
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.
The numpy.array is not the same as the standard Python library class array.

### Syntax for numpy array

variableName=np.array([data 1,data 2,data 3,.....,data n])

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4,5])

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1)

numpy.ndarray

Numpy arrays can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of an array.



1 Dimensional Array

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1.shape

(5,)

2 Dimensional Array

In [ ]:
arr2=np.array([[10,20,30],
               [40,50,60]])

In [ ]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr2.shape

(2, 3)

Multidimensional Array

In [ ]:
arr3=np.array([[[1,2,3],
               [4,5,6]],
               [[7,8,9],
                [10,11,12]]])

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr3.shape

(2, 2, 3)

# Numpy array Functions

### 1.numpy.concatenate()

The concatenate() function is a function from the NumPy package. This function combines two or more numpy arrays together along a specific axis.
 

Syntax : 

numpy.concatenate((a1,a2,a3,.....),axis)

Example 1:


In [ ]:
a1=np.array([12,13,14])

In [ ]:
a2=np.array([15,16,17])

In [ ]:
np.concatenate((a1,a2),axis=0)

array([12, 13, 14, 15, 16, 17])

Example 2:

In [ ]:
a3=np.array([[1,2,3],
             [4,5,6]])

In [ ]:
a4=np.array([[7,8,9],
             [10,11,12]])

In [ ]:
np.concatenate((a3,a4),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Example 3:

In [ ]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a1

array([12, 13, 14])

In [ ]:
np.concatenate((a1,a3),axis=0)

ValueError: ignored

The above code does not execute as the dimension of array-a3 and array-a1 are different, a3 is 2 dimensional array while a1 is 1 dimensional array. So, arrays of different dimensions cannot be concatenated. 

### 2.numpy.append()

The numpy.append() function is available in NumPy package. Append means adding elements. The numpy.append() function is used to add or append new values to an existing numpy array. The new values gets added at the end of the array.

Example 1:

In [ ]:
a=np.array([11,22,33])

In [ ]:
b=np.array([44,55,66])

In [ ]:
c=np.append(a,b)
c

array([11, 22, 33, 44, 55, 66])

Example 2:

In [ ]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.append(a3,a4)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.append(a3,a4,axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:

np.append(a3,a4,axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:

np.append(a,a3)

array([11, 22, 33,  1,  2,  3,  4,  5,  6])

In [ ]:
np.append(a,a3,axis=0)

ValueError: ignored

The above code does not execute as the dimension of array-a3 and array-a1 are different, a3 is 2 dimensional array while a1 is 1 dimensional array. So, arrays of different dimensions cannot be appened or added in the axis that is equal to 0. 

#### 3.numpy.transpose()

The numpy.transpose() function is one of the most important functions in matrix multiplication. This function reserves the dimension of the given array and returns the modified array.
The numpy.transpose() function changes the row elements into column elements and the column elements into row elements. The output of this function is a modified array of the original one.

Syntax :

numpy.transpose(arr,axis=None)

Example 1:

In [ ]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a3)

array([[1, 4],
       [2, 5],
       [3, 6]])

Example 2:

In [ ]:
a5=np.array([[[21,31,41],
      [51,61,71]],

      [[71,81,91],
      [11,12,13]],
     
      [[1,2,3],
     [4,5,6]]])

In [ ]:
a5

array([[[21, 31, 41],
        [51, 61, 71]],

       [[71, 81, 91],
        [11, 12, 13]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [ ]:
a5.shape

(3, 2, 3)

In [ ]:
np.transpose(a5)

array([[[21, 71,  1],
        [51, 11,  4]],

       [[31, 81,  2],
        [61, 12,  5]],

       [[41, 91,  3],
        [71, 13,  6]]])

### 4.numpy.sum()

The numpy.sum() function is available in the NumPy package of Python. This function is used to compute the sum of all elements, the sum of each row, and the sum of each column of a given array. It returns the sum of all in the elements in the numpy array. This avoids the using of loop which we do in python but with the help of numpy we can easily write it without using loop

Syntax :

variableName=np.sum(arrayName)

Example 1:

In [ ]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.sum(a3)

21

Example 2:

In [ ]:
sum1=np.array([1,2,2.2,3,3.3])

In [ ]:
x=np.sum(sum1,dtype=np.int32)

In [ ]:
x

11

Here, only integer value will be considered if dtype=int32 is mentioned. Even if the number is float, only the integer part of the float number will be taken into consideration for calculation of the sum.

Example 3:

In [ ]:
a5

array([[[21, 31, 41],
        [51, 61, 71]],

       [[71, 81, 91],
        [11, 12, 13]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

In [ ]:
np.sum(a5)

576

### 5.numpy.dot()

The Numpy library provides a built-in function to compute the dot product of two vectors.

This function returns the dot product of 'a' and 'b'. This function returns a scalar if 'a' and 'b' are both scalars or 1-dimensional; otherwise, it returns an array. If 'out' is given, then it is returned.

Syntax : 

variableName=np.dot(array1,array2)

Example 1:

In [ ]:
kanto=np.array([73,67,43])

In [ ]:
w1,w2,w3=0.3,0.2,0.5

In [ ]:
weights=np.array([w1,w2,w3])

In [ ]:
np.dot(kanto,weights)

56.8

Example 2:

In [ ]:
a_dot=np.dot(7,13)

In [ ]:
a_dot

91

Example 3:

In [ ]:
a_dot1=np.dot([2j,3j],[5j,1j])

In [ ]:
a_dot1

(-13+0j)

Example 4:

In [ ]:
a=np.array([[1,2],[4,2]])

In [ ]:
b=np.array([[3,5],[2,1]])

In [ ]:
c=np.dot(a,b)
c

array([[ 7,  7],
       [16, 22]])

Here's a comparison of `dot` products performed using Python loops vs. Numpy arrays on two vectors with a million elements each.

In [ ]:
#Python lists
p_arr1=list(range(1000000))
p_arr2=list(range(1000000,2000000))

#Numpy arrays
np_arr1=np.array(p_arr1)
np_arr2=np.array(p_arr2)

In [ ]:
%%time
result=0
for x1,x2 in zip(p_arr1,p_arr2):
    result += x1*x2
result 

CPU times: user 166 ms, sys: 15 µs, total: 166 ms
Wall time: 171 ms


833332333333500000

In [ ]:
%%time
np.dot(np_arr1,np_arr2)

CPU times: user 2.16 ms, sys: 0 ns, total: 2.16 ms
Wall time: 1.38 ms


833332333333500000

%%time - used to calculate the time taken to run the program

As you can see, using np.dot is 100 times faster than using a for loop. This makes Numpy especially useful while working with really large datasets with tens of thousands or millions of data points.

Example 5:

In [ ]:
a1

array([12, 13, 14])

In [ ]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.dot(a1,a3)

ValueError: ignored

The above code does not execute as the dimension and shape of array-a3 and array-a1 are different, a3 is 2 dimensional array with shape (2,3) while a1 is 1 dimensional array with shape (3,). So, arrays of different dimensions and shapes cannot be considered to compute their dot product.

### 6. numpy.mean()

The numpy.mean() function is used to compute the arithmetic mean along the specified axis.

This function returns the average of the array elements. By default, the average is taken on the flattened array. Else on the specified axis, float 64 is intermediate as well as return values are used for integer inputs

Syntax:

np.mean(parameters)

Example 1:

In [ ]:
a_mean=np.array([[1,2],[4,2]])

In [ ]:
b_mean=np.mean(a_mean)
b_mean

2.25

Example 2:

In [ ]:
x_mean=np.array([[5,6],[7,8]])

In [ ]:
y_mean=np.mean(x_mean)
y_mean

6.5

Example 3:

In [ ]:
a_mean

array([[1, 2],
       [4, 2]])

In [ ]:
b_mean2=np.mean(a_mean,axis=0)
b_mean2

array([2.5, 2. ])

In [ ]:
c_mean=np.mean(a_mean,axis=1)
c_mean

array([1.5, 3. ])

Example 4 : Adding two arrays and finding the mean of the sum of the arrays

In [ ]:
a_mean

array([[1, 2],
       [4, 2]])

In [ ]:
x_mean

array([[5, 6],
       [7, 8]])

In [ ]:
sum=a_mean + x_mean
sum

array([[ 6,  8],
       [11, 10]])

In [ ]:
np.mean(sum)

8.75

### 7. numpy.sort()

The numpy.sort() function is available in the NumPy package of Python. This function is used to sort the elements in the array in ascending order. This function returns a sorted copy of the source array, which will have the same shape and type as a source array.

Syntax : 

numpy.sort(arrayName,axis,order)

Example 1:

In [ ]:
x_sort=np.array([[ 1,  4,  2,  3],
       	[ 9, 13, 61,  1],
       	[43, 24, 88, 22]])
x_sort

array([[ 1,  4,  2,  3],
       [ 9, 13, 61,  1],
       [43, 24, 88, 22]])

In [ ]:
np.sort(x_sort)

array([[ 1,  2,  3,  4],
       [ 1,  9, 13, 61],
       [22, 24, 43, 88]])

In [ ]:
np.sort(x_sort,axis=0)

array([[ 1,  4,  2,  1],
       [ 9, 13, 61,  3],
       [43, 24, 88, 22]])

In [ ]:
np.sort(x_sort,axis=None)

array([ 1,  1,  2,  3,  4,  9, 13, 22, 24, 43, 61, 88])

Example 2:

In [ ]:
x_sort

array([[ 1,  4,  2,  3],
       [ 9, 13, 61,  1],
       [43, 24, 88, 22]])

In [ ]:
y_sort=([[ 10,  4,  12,  33],
       [ 29, 23, 1,  11],
       [93, 64, 58, 32]])
y_sort

[[10, 4, 12, 33], [29, 23, 1, 11], [93, 64, 58, 32]]

In [ ]:
sort_xy=x_sort + y_sort
sort_xy

array([[ 11,   8,  14,  36],
       [ 38,  36,  62,  12],
       [136,  88, 146,  54]])

In [ ]:
np.sort(sort_xy)

array([[  8,  11,  14,  36],
       [ 12,  36,  38,  62],
       [ 54,  88, 136, 146]])

### 8. numpy.linspace()

The numpy.linspace() function is available in the NumPy package of Python. It returns evenly separated values over a specified period.

Syntax : 

numpy.linspace(start, stop, num, endpoint)   

Example 1:

In [ ]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

Example 2:

In [ ]:
np.linspace(5,100,10)

array([  5.        ,  15.55555556,  26.11111111,  36.66666667,
        47.22222222,  57.77777778,  68.33333333,  78.88888889,
        89.44444444, 100.        ])

Example 3:

In [ ]:
np.linspace(10, 20, 5, endpoint = False)  

array([10., 12., 14., 16., 18.])

### 8. numpy.unique()

The numpy module of Python provides a function for finding unique elements in a numpy array. The numpy.unique() function finds the unique elements of an array and returns these unique elements as a sorted array.

Example 1:

In [ ]:
a=np.unique([1,20,3,5,3,6,20,5])  
a

array([ 1,  3,  5,  6, 20])

Example 2:

In [ ]:
x_unique=np.array([[ 1,  4,  2,  3],
       [ 9, 3, 6,  1],
       [3, 4, 6, 2]])
x_unique

array([[1, 4, 2, 3],
       [9, 3, 6, 1],
       [3, 4, 6, 2]])

In [ ]:
np.unique(x_unique)

array([1, 2, 3, 4, 6, 9])

### 9. numpy.arrage()

The numpy.arrange() function is available in the NumPy package of Python.
It creates an array by using the evenly spaced values over the given interval.

Syntax : 

numpy.arrange(start, stop, step, dtype)  

Example 1:

In [ ]:
a_arrange=np.arange(10,90,3)
a_arrange

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [ ]:
a_arrange.shape

(27,)

In [ ]:
a_arrange.reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

Example 2:

In [ ]:
arr=np.arange(0,10,2,float)
arr

array([0., 2., 4., 6., 8.])

Here, in the output we get elements in floating data type and not in integer as we have mentioned the dtype to be float

### 10. numpy.asarray()

This function is used to create an array by using the existing data in the form of lists, or tuples. This function is useful in the scenario where we need to convert a python sequence into the numpy array object.

Example 1:

In [ ]:
k=[[ 1,  4,  2,  3],
       	[ 9, 13, 61,  1],
       	[43, 24, 88, 22]]
k

[[1, 4, 2, 3], [9, 13, 61, 1], [43, 24, 88, 22]]

In [ ]:
type(k)

list

In [ ]:
k=np.asarray(k)

In [ ]:
k

array([[ 1,  4,  2,  3],
       [ 9, 13, 61,  1],
       [43, 24, 88, 22]])

In [ ]:
type(k)

numpy.ndarray